name: messenger
description: A Flutter messenger app
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.3.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.0

  file_picker: ^8.0.0
  image_picker: ^1.0.7

  intl: ^0.19.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
